import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import * as readline from 'readline';
import chalk from 'chalk';

/**
 * Interactive prompt helper using readline
 */
function createPrompt(): {
  ask: (question: string, defaultValue?: string) => Promise<string>;
  confirm: (question: string, defaultValue?: boolean) => Promise<boolean>;
  close: () => void;
} {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return {
    ask: (question: string, defaultValue?: string): Promise<string> => {
      const defaultHint = defaultValue ? ` (${defaultValue})` : '';
      return new Promise((resolve) => {
        rl.question(`${question}${defaultHint}: `, (answer) => {
          resolve(answer.trim() || defaultValue || '');
        });
      });
    },
    confirm: (question: string, defaultValue = false): Promise<boolean> => {
      const hint = defaultValue ? '(Y/n)' : '(y/N)';
      return new Promise((resolve) => {
        rl.question(`${question} ${hint}: `, (answer) => {
          const normalized = answer.trim().toLowerCase();
          if (normalized === '') {
            resolve(defaultValue);
          } else {
            resolve(normalized === 'y' || normalized === 'yes');
          }
        });
      });
    },
    close: () => rl.close(),
  };
}

interface InitConfig {
  useCustomProvider: boolean;
  provider?: {
    name: string;
    npm: string;
    baseURL: string;
    apiKeyEnvVar: string;
    modelId: string;
    modelDisplayName: string;
  };
  defaultModel: string;
  agents: string[];
  agentModels: Record<string, string>;
}

/**
 * Generate drs.config.yaml content from init config
 */
function generateConfigYaml(config: InitConfig): string {
  let yaml = `# DRS Configuration
# Generated by: drs init
# Documentation: https://github.com/manojlds/drs

`;

  // Add custom provider if configured
  if (config.useCustomProvider && config.provider) {
    yaml += `# Custom AI Provider
opencode:
  provider:
    ${config.provider.name}:
      npm: "${config.provider.npm}"
      name: "${config.provider.name}"
      options:
        baseURL: "${config.provider.baseURL}"
        apiKey: "{env:${config.provider.apiKeyEnvVar}}"
      models:
        ${config.provider.modelId}:
          name: "${config.provider.modelDisplayName}"

`;
  }

  yaml += `review:
  # Default model for all agents
  defaultModel: ${config.defaultModel}

  # Review agents
  agents:
`;

  // Add agents with optional model overrides
  for (const agent of config.agents) {
    const agentModel = config.agentModels[agent];
    if (agentModel && agentModel !== config.defaultModel) {
      yaml += `    - name: ${agent}
      model: ${agentModel}
`;
    } else {
      yaml += `    - ${agent}
`;
    }
  }

  yaml += `
  # Files to ignore during review
  ignorePatterns:
    - "*.test.ts"
    - "*.spec.ts"
    - "**/__tests__/**"
    - "**/__mocks__/**"
    - "*.md"
    - "package-lock.json"
    - "yarn.lock"
    - "pnpm-lock.yaml"
`;

  return yaml;
}

const DEFAULT_GLOBAL_CONTEXT = `# Project Context

## Architecture
<!-- Describe your system architecture -->

## Technology Stack
<!-- List your main technologies, frameworks, and tools -->

## Trust Boundaries
<!-- Explain what inputs are trusted vs untrusted -->

## Review Guidelines
<!-- Any project-specific guidelines for reviewers -->
`;

const AGENT_CONTEXT_TEMPLATE = `# {AGENT} Agent Context

## Project-Specific Rules

### What NOT to Flag
<!-- List patterns that are valid for your project -->

### What TO Flag
<!-- List concerns specific to your project -->

## Severity Calibration
- **CRITICAL**: Actively exploitable issues with high impact
- **HIGH**: Real issues requiring immediate attention
- **MEDIUM**: Potential edge cases or hardening opportunities
- **LOW**: Best practice improvements
`;

const AGENTS_README = `# DRS Agent Customization

DRS supports three levels of agent customization:

## 1. Global Context (.drs/context.md)

Project-wide context applied to ALL agents. Use this for:
- Architecture overview
- Technology stack
- Trust boundaries
- General review guidelines

## 2. Agent-Specific Context (.drs/agents/{name}/context.md)

**Additive** - Enhances the default agent with project-specific rules.

Example: \`.drs/agents/security/context.md\`
\`\`\`markdown
# Security Agent Context

## What NOT to Flag
- process.env for configuration (standard practice)
- Data from trusted APIs

## What TO Flag
- SQL injection vulnerabilities
- XSS in user-facing endpoints
\`\`\`

## 3. Full Agent Override (.drs/agents/{name}/agent.md)

**Replacement** - Completely replaces the default agent.

Example: \`.drs/agents/security/agent.md\`
\`\`\`markdown
---
description: Custom security reviewer
tools:
  Read: true
  Grep: true
---

You are a security expert specialized in [your domain].

[Complete custom instructions here]
\`\`\`

## Custom Agents

Create a new folder for custom agents:
\`.drs/agents/rails-reviewer/agent.md\`

Then add to \`.drs/drs.config.yaml\`:
\`\`\`yaml
review:
  agents:
    - security
    - quality
    - rails-reviewer  # Your custom agent
\`\`\`

## Learn More

- [DRS Documentation](https://github.com/manojlds/drs)
`;

/**
 * Initialize DRS configuration in a project with interactive prompts
 */
export async function initProject(projectPath: string): Promise<void> {
  console.log(chalk.bold.cyan('\n📋 DRS | Diff Review System Setup\n'));

  const prompt = createPrompt();

  try {
    // Check if already initialized
    const drsDir = join(projectPath, '.drs');
    const configPath = join(drsDir, 'drs.config.yaml');

    if (existsSync(configPath)) {
      const overwrite = await prompt.confirm(
        chalk.yellow('⚠ .drs/drs.config.yaml already exists. Overwrite?'),
        false
      );
      if (!overwrite) {
        console.log(chalk.gray('\nInit cancelled. Existing config preserved.\n'));
        prompt.close();
        return;
      }
    }

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // STEP 1: Custom Provider
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    console.log(chalk.bold('\n━━━ AI Provider ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n'));

    const initConfig: InitConfig = {
      useCustomProvider: false,
      defaultModel: '',
      agents: [],
      agentModels: {},
    };

    initConfig.useCustomProvider = await prompt.confirm(
      'Do you need a custom OpenAI-compatible provider?',
      false
    );

    if (initConfig.useCustomProvider) {
      console.log(chalk.gray('\nConfiguring custom provider...\n'));

      const providerName = await prompt.ask('Provider name', 'custom');
      const npm = await prompt.ask('NPM package', '@ai-sdk/openai-compatible');
      const baseURL = await prompt.ask('Base URL');
      const apiKeyEnvVar = await prompt.ask('API key environment variable name', 'OPENAI_API_KEY');
      const modelId = await prompt.ask('Model identifier');
      const modelDisplayName = await prompt.ask('Model display name', modelId);

      initConfig.provider = {
        name: providerName,
        npm,
        baseURL,
        apiKeyEnvVar,
        modelId,
        modelDisplayName,
      };

      initConfig.defaultModel = `${providerName}/${modelId}`;
      console.log(chalk.green(`\n✓ Custom provider "${providerName}" configured`));
    }

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // STEP 2: Model Configuration
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    console.log(chalk.bold('\n━━━ Model Configuration ━━━━━━━━━━━━━━━━━━━━━━━━━━━\n'));

    if (!initConfig.useCustomProvider) {
      console.log(chalk.gray('Common models:'));
      console.log(chalk.gray('  • anthropic/claude-sonnet-4-5-20250929 (balanced)'));
      console.log(chalk.gray('  • anthropic/claude-opus-4-5-20251101 (premium)'));
      console.log(chalk.gray('  • openai/gpt-4o (OpenAI)'));
      console.log(chalk.gray('  • zhipuai/glm-4.7 (budget)\n'));

      initConfig.defaultModel = await prompt.ask(
        'Default model for all agents',
        'anthropic/claude-sonnet-4-5-20250929'
      );
    } else {
      console.log(chalk.gray(`Using custom provider model: ${initConfig.defaultModel}\n`));
    }

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // STEP 3: Agent Selection
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    console.log(chalk.bold('\n━━━ Review Agents ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n'));

    const availableAgents = ['security', 'quality', 'style', 'performance'];

    console.log(chalk.gray('Available agents:'));
    console.log(chalk.gray('  • security     - Security vulnerabilities & best practices'));
    console.log(chalk.gray('  • quality      - Code quality & maintainability'));
    console.log(chalk.gray('  • style        - Code style & consistency'));
    console.log(chalk.gray('  • performance  - Performance issues & optimizations\n'));

    const agentsInput = await prompt.ask(
      'Agents to enable (comma-separated)',
      'security,quality,style,performance'
    );

    initConfig.agents = agentsInput
      .split(',')
      .map((a) => a.trim().toLowerCase())
      .filter((a) => a.length > 0);

    // Validate agents
    const invalidAgents = initConfig.agents.filter((a) => !availableAgents.includes(a));
    if (invalidAgents.length > 0) {
      console.log(chalk.yellow(`\n⚠ Custom agents detected: ${invalidAgents.join(', ')}`));
      console.log(
        chalk.gray("  You'll need to create agent definitions in .drs/agents/{name}/agent.md")
      );
    }

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // STEP 4: Per-Agent Model Overrides
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    console.log(chalk.bold('\n━━━ Per-Agent Model Overrides ━━━━━━━━━━━━━━━━━━━━━\n'));

    const configureOverrides = await prompt.confirm(
      'Configure different models for specific agents?',
      false
    );

    if (configureOverrides) {
      console.log(chalk.gray(`\nPress Enter to use default (${initConfig.defaultModel})\n`));

      for (const agent of initConfig.agents) {
        const model = await prompt.ask(`Model for ${agent}`);
        if (model && model !== initConfig.defaultModel) {
          initConfig.agentModels[agent] = model;
        }
      }
    }

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // Create files
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    console.log(chalk.bold('\n━━━ Creating Files ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n'));

    // Create .drs directory
    if (!existsSync(drsDir)) {
      mkdirSync(drsDir, { recursive: true });
    }

    // Create drs.config.yaml
    writeFileSync(configPath, generateConfigYaml(initConfig), 'utf-8');
    console.log(chalk.green('✓'), 'Created', chalk.cyan('.drs/drs.config.yaml'));

    // Create global context file
    const contextPath = join(drsDir, 'context.md');
    if (!existsSync(contextPath)) {
      writeFileSync(contextPath, DEFAULT_GLOBAL_CONTEXT, 'utf-8');
      console.log(chalk.green('✓'), 'Created', chalk.cyan('.drs/context.md'));
    } else {
      console.log(chalk.yellow('⚠'), chalk.cyan('.drs/context.md'), 'already exists');
    }

    // Create agents directory
    const agentsDir = join(drsDir, 'agents');
    if (!existsSync(agentsDir)) {
      mkdirSync(agentsDir, { recursive: true });
    }

    // Create agent context templates for selected agents
    for (const agentName of initConfig.agents) {
      const agentDir = join(agentsDir, agentName);
      if (!existsSync(agentDir)) {
        mkdirSync(agentDir, { recursive: true });

        const agentContextPath = join(agentDir, 'context.md');
        const contextContent = AGENT_CONTEXT_TEMPLATE.replace(
          '{AGENT}',
          agentName.charAt(0).toUpperCase() + agentName.slice(1)
        );
        writeFileSync(agentContextPath, contextContent, 'utf-8');
      }
    }
    console.log(chalk.green('✓'), 'Created agent context templates in', chalk.cyan('.drs/agents/'));

    // Create agents README
    const agentsReadmePath = join(agentsDir, 'README.md');
    if (!existsSync(agentsReadmePath)) {
      writeFileSync(agentsReadmePath, AGENTS_README, 'utf-8');
      console.log(chalk.green('✓'), 'Created', chalk.cyan('.drs/agents/README.md'));
    }

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // Summary
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    console.log(chalk.bold.green('\n✓ DRS initialization complete!\n'));

    console.log(chalk.bold('Configuration Summary:'));
    console.log(
      `  Provider: ${initConfig.useCustomProvider ? initConfig.provider?.name : 'Built-in (Anthropic/OpenAI/etc)'}`
    );
    console.log(`  Default Model: ${initConfig.defaultModel}`);
    console.log(`  Agents: ${initConfig.agents.join(', ')}`);

    if (Object.keys(initConfig.agentModels).length > 0) {
      console.log('  Model Overrides:');
      for (const [agent, model] of Object.entries(initConfig.agentModels)) {
        console.log(`    • ${agent}: ${model}`);
      }
    }

    console.log(chalk.bold('\nNext steps:\n'));

    // Determine which API key is needed
    let apiKeyHint: string;
    if (initConfig.useCustomProvider && initConfig.provider) {
      apiKeyHint = `export ${initConfig.provider.apiKeyEnvVar}=your-key`;
    } else if (initConfig.defaultModel.startsWith('anthropic/')) {
      apiKeyHint = 'export ANTHROPIC_API_KEY=your-key';
    } else if (initConfig.defaultModel.startsWith('openai/')) {
      apiKeyHint = 'export OPENAI_API_KEY=your-key';
    } else {
      apiKeyHint = 'export <PROVIDER>_API_KEY=your-key';
    }

    console.log(`  1. Set API key: ${chalk.cyan(apiKeyHint)}`);
    console.log(`  2. Edit project context: ${chalk.cyan('.drs/context.md')}`);
    console.log(
      `  3. Run a review: ${chalk.cyan('drs review-pr --pr <number> --owner <owner> --repo <repo>')}`
    );
    console.log('');

    prompt.close();
  } catch (error) {
    prompt.close();
    throw error;
  }
}
