# Example GitHub Actions workflow for DRS PR review
# Place this in .github/workflows/pr-review.yml in your repository

name: DRS PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install DRS
        run: npm install -g @drs/gitlab-review-bot

      - name: Review Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          # Optional: Customize review agents
          # REVIEW_AGENTS: security,quality,style,performance
        run: |
          drs review-pr \
            --owner ${{ github.event.repository.owner.login }} \
            --repo ${{ github.event.repository.name }} \
            --pr ${{ github.event.pull_request.number }} \
            --post-comments

      # Optional: Fail build if critical issues found
      # The review-pr command exits with code 1 if critical issues are found
