# Example GitLab CI configuration for DRS
# Add this to your .gitlab-ci.yml file

stages:
  - review
  - test
  - deploy

# AI Code Review
ai_review:
  stage: review
  image: node:20
  only:
    - merge_requests
  script:
    - npm install -g @diff-review-system/drs
    - drs review-mr --mr $CI_MERGE_REQUEST_IID --project $CI_PROJECT_ID --post-comments
  variables:
    OPENCODE_SERVER: "http://opencode.internal:3000"
    GITLAB_TOKEN: $CI_JOB_TOKEN
  allow_failure: true
