# DRS GitLab CI Template
# Include this in your .gitlab-ci.yml:
#
# include:
#   - remote: 'https://raw.githubusercontent.com/your-org/drs/main/templates/gitlab-ci.yml'

.drs_review:
  stage: review
  image: node:20
  only:
    - merge_requests
  script:
    - npm install -g @drs/gitlab-review-bot
    - drs review-mr --mr $CI_MERGE_REQUEST_IID --project $CI_PROJECT_ID --post-comments
  variables:
    # OpenCode Server URL (required)
    OPENCODE_SERVER: "${OPENCODE_SERVER}"

    # GitLab Token (use CI_JOB_TOKEN for automatic auth)
    GITLAB_TOKEN: "${CI_JOB_TOKEN}"

    # GitLab URL (optional, defaults to https://gitlab.com)
    GITLAB_URL: "${CI_SERVER_URL}"

    # Review agents to use (optional)
    # REVIEW_AGENTS: "security,quality,style,performance"

  # Allow job to fail without blocking pipeline
  allow_failure: true

  # Artifacts (optional - save review results)
  # artifacts:
  #   reports:
  #     codequality: gl-code-quality-report.json
  #   when: always
  #   expire_in: 1 week

# Full review with all agents
ai_review_full:
  extends: .drs_review
  variables:
    REVIEW_AGENTS: "security,quality,style,performance"

# Quick security-only review
ai_review_security:
  extends: .drs_review
  variables:
    REVIEW_AGENTS: "security"
  allow_failure: false  # Block on security issues
